spring:
  application:
    name: apache-kafka.testing
  kafka:
    #define zoo-keeper-server port
    bootstrap-servers: localhost:9092
    #add topic for consumer
    topics:
      testing-event: my-testing-topic
    groups:
      testing-group: my-testing-group
